name: Build and Test Package
on: [push, pull_request]
jobs:
  build:
    name: Packaging and Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel pylint
      - name: Static Analysis with pylint
        run: |
          pylint spotfire
      - name: Packaging
        run: |
          python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: 'dist/**'
  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_dev.txt
      - name: Run Tests
        run: |
          python -m spotfire.test
      - uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.python-version }}
          path: 'results-*.xml'

